version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - patrykjadamczyk
  assignees:
  - patrykjadamczyk
  ignore:
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
